// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npjgkmandydzjoemniok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wamdrbWFuZHlkempvZW1uaW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NzU0MDQsImV4cCI6MjA4NDU1MTQwNH0.LQIClZPshuVkeKsvzWFzcW58uH9ncjTigUGYoCMz6W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
